In [1]:
!wget -O loan_train.csv https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/loan_train.csv

--2020-09-21 16:49:18--  https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/loan_train.csv
Resolving s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)... 67.228.254.196
Connecting to s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)|67.228.254.196|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23101 (23K) [text/csv]
Saving to: ‘loan_train.csv’

100%[======================================>] 23,101      --.-K/s   in 0.002s  

2020-09-21 16:49:18 (12.9 MB/s) - ‘loan_train.csv’ saved [23101/23101]



In [8]:
df = pd.read_csv("https://s3.us.cloud-object-storage.appdomain.cloud/cf-courses-data/CognitiveClass/DP0701EN/version-2/Data-Collisions.csv")
df.head()

/opt/conda/envs/Python36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY REPORTNO  \
0             2 -122.323148  47.703140         1    1307       1307  3502005   
1             1 -122.347294  47.647172         2   52200      52200  2607959   
2             1 -122.334540  47.607871         3   26700      26700  1482393   
3             1 -122.334803  47.604803         4    1144       1144  3503937   
4             2 -122.306426  47.545739         5   17700      17700  1807429   

    STATUS      ADDRTYPE   INTKEY  ... ROADCOND                LIGHTCOND  \
0  Matched  Intersection  37475.0  ...      Wet                 Daylight   
1  Matched         Block      NaN  ...      Wet  Dark - Street Lights On   
2  Matched         Block      NaN  ...      Dry                 Daylight   
3  Matched         Block      NaN  ...      Dry                 Daylight   
4  Matched  Intersection  34387.0  ...      Wet                 Daylight   

  PEDROWNOTGRNT  SDOTCOLNUM SPEEDING ST_COLCODE  \
0           NaN         NaN      NaN         10   
1           NaN   6354039.0      NaN         11   
2           NaN   4323031.0      NaN         32   
3           NaN         NaN      NaN         23   
4           NaN   4028032.0      NaN         10   

                                          ST_COLDESC  SEGLANEKEY  \
0                                  Entering at angle           0   
1  From same direction - both going straight - bo...           0   
2                             One parked--one moving           0   
3                   From same direction - all others           0   
4                                  Entering at angle           0   

   CROSSWALKKEY  HITPARKEDCAR  
0             0             N  
1             0             N  
2             0             N  
3             0             N  
4             0             N  

[5 rows x 38 columns]

In [9]:
import numpy as np


In [10]:
import pandas as pd

In [11]:
df.dtypes

SEVERITYCODE        int64
X                 float64
Y                 float64
OBJECTID            int64
INCKEY              int64
COLDETKEY           int64
REPORTNO           object
STATUS             object
ADDRTYPE           object
INTKEY            float64
LOCATION           object
EXCEPTRSNCODE      object
EXCEPTRSNDESC      object
SEVERITYCODE.1      int64
SEVERITYDESC       object
COLLISIONTYPE      object
PERSONCOUNT         int64
PEDCOUNT            int64
PEDCYLCOUNT         int64
VEHCOUNT            int64
INCDATE            object
INCDTTM            object
JUNCTIONTYPE       object
SDOT_COLCODE        int64
SDOT_COLDESC       object
INATTENTIONIND     object
UNDERINFL          object
WEATHER            object
ROADCOND           object
LIGHTCOND          object
PEDROWNOTGRNT      object
SDOTCOLNUM        float64
SPEEDING           object
ST_COLCODE         object
ST_COLDESC         object
SEGLANEKEY          int64
CROSSWALKKEY        int64
HITPARKEDCAR       object
dtype: objec

In [12]:
from sklearn.utils import resample

In [13]:
df_maj=df[df.SEVERITYCODE==1]
df_min=df[df.SEVERITYCODE==2]
df_maj_dsample=resample(df_maj, replace=False, n_samples=58188, random_state=123)
balanced_df=pd.concat([df_maj_dsample, df_min])
balanced_df.SEVERITYCODE.value_counts()


2    58188
1    58188
Name: SEVERITYCODE, dtype: int64

In [14]:
x=np.asarray(balanced_df[['WEATHER', 'ROADCOND', 'LIGHTCOND']])
x[0:5]

array([['Raining', 'Wet', 'Dark - Street Lights On'],
       ['Clear', 'Dry', 'Daylight'],
       ['Unknown', 'Unknown', 'Unknown'],
       ['Clear', 'Dry', 'Daylight'],
       ['Clear', 'Dry', 'Daylight']], dtype=object)

In [15]:
balanced_df.head()

SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY  \
25055              1 -122.292730  47.719265     29626   43684      43684   
65280              1 -122.329124  47.608658     71557   84514      84514   
86292              1 -122.292434  47.733753     94574  110476     110476   
155111             1         NaN        NaN    172907  222604     222884   
64598              1 -122.339185  47.625594     70842   84273      84273   

       REPORTNO   STATUS      ADDRTYPE   INTKEY  ... ROADCOND  \
25055   1778514  Matched  Intersection  36599.0  ...      Wet   
65280   2623093  Matched  Intersection  29926.0  ...      Dry   
86292   3377452  Matched  Intersection  35987.0  ...  Unknown   
155111  E554578  Matched         Block      NaN  ...      Dry   
64598   2898917  Matched         Block      NaN  ...      Dry   

                      LIGHTCOND PEDROWNOTGRNT  SDOTCOLNUM SPEEDING ST_COLCODE  \
25055   Dark - Street Lights On           NaN   5022026.0      NaN         10   
65280                  Daylight           NaN   8235027.0      NaN         10   
86292                   Unknown           NaN  10323017.0      NaN         10   
155111                 Daylight           NaN         NaN      NaN         11   
64598                  Daylight           NaN   8069016.0      NaN         30   

                                               ST_COLDESC  SEGLANEKEY  \
25055                                   Entering at angle           0   
65280                                   Entering at angle           0   
86292                                   Entering at angle           0   
155111  From same direction - both going straight - bo...           0   
64598                From opposite direction - all others           0   

        CROSSWALKKEY  HITPARKEDCAR  
25055              0             N  
65280              0             N  
86292              0             N  
155111             0             N  
64598              0             N  

[5 rows x 38 columns]

In [16]:
final_df=balanced_df[['SEVERITYCODE','WEATHER', 'ROADCOND', 'LIGHTCOND']]
final_df.head()

SEVERITYCODE  WEATHER ROADCOND                LIGHTCOND
25055              1  Raining      Wet  Dark - Street Lights On
65280              1    Clear      Dry                 Daylight
86292              1  Unknown  Unknown                  Unknown
155111             1    Clear      Dry                 Daylight
64598              1    Clear      Dry                 Daylight

In [17]:
final_df.dtypes


SEVERITYCODE     int64
WEATHER         object
ROADCOND        object
LIGHTCOND       object
dtype: object

In [18]:
final_df.dropna()

SEVERITYCODE            WEATHER ROADCOND                 LIGHTCOND
25055              1            Raining      Wet   Dark - Street Lights On
65280              1              Clear      Dry                  Daylight
86292              1            Unknown  Unknown                   Unknown
155111             1              Clear      Dry                  Daylight
64598              1              Clear      Dry                  Daylight
119954             1              Clear      Dry                  Daylight
64063              1              Clear      Dry                  Daylight
105379             1              Clear      Dry                  Daylight
187708             1              Clear      Dry                  Daylight
63021              1            Unknown  Unknown                  Daylight
156744             1              Clear      Dry   Dark - Street Lights On
10240              1              Clear      Dry                      Dusk
37311              1              Clear      Dry                  Daylight
108465             1              Clear      Dry                  Daylight
97400              1              Clear      Dry   Dark - Street Lights On
51928              1            Raining      Wet   Dark - Street Lights On
7574               1           Overcast      Dry                  Daylight
135430             1              Other  Unknown                   Unknown
64620              1              Clear      Dry                  Daylight
160199             1            Raining      Wet                  Daylight
169301             1              Clear      Dry                      Dawn
120192             1           Overcast      Wet   Dark - Street Lights On
158305             1              Clear      Dry                  Daylight
179658             1              Clear      Dry                      Dusk
67340              1              Clear      Dry                  Daylight
184250             1            Unknown  Unknown                   Unknown
57004              1              Clear      Dry                  Daylight
49555              1           Overcast      Dry                  Daylight
74905              1            Unknown  Unknown                   Unknown
187234             1              Clear      Dry                  Daylight
...              ...                ...      ...                       ...
194565             2              Clear      Dry                  Daylight
194576             2            Raining      Wet                  Daylight
194578             2              Clear      Dry   Dark - Street Lights On
194579             2            Raining      Wet                  Daylight
194589             2              Clear      Dry   Dark - Street Lights On
194594             2              Clear      Dry                  Daylight
194602             2            Raining      Wet                  Daylight
194608             2            Raining      Wet                  Daylight
194613             2              Clear      Dry                  Daylight
194615             2              Clear      Dry   Dark - Street Lights On
194627             2            Raining      Wet                  Daylight
194631             2  Blowing Sand/Dirt      Wet   Dark - Street Lights On
194633             2              Clear      Dry   Dark - Street Lights On
194634             2           Overcast      Wet   Dark - Street Lights On
194636             2              Clear      Wet                  Daylight
194637             2            Raining      Wet                  Daylight
194640             2           Overcast      Wet  Dark - Street Lights Off
194645             2              Clear      Dry   Dark - Street Lights On
194647             2            Raining      Wet                      Dusk
194649             2              Clear      Dry   Dark - Street Lights On
194650             2              Clear      Dry                  Daylight
194653             2           Ov

In [19]:
final_df["WEATHER"].value_counts()

Clear                       67946
Raining                     20584
Overcast                    16834
Unknown                      6851
Snowing                       474
Other                         406
Fog/Smog/Smoke                355
Sleet/Hail/Freezing Rain       63
Blowing Sand/Dirt              30
Severe Crosswind               13
Partly Cloudy                   4
Name: WEATHER, dtype: int64

In [20]:
final_df["ROADCOND"].value_counts()

Dry               76000
Wet               29374
Unknown            6806
Ice                 678
Snow/Slush          528
Other                83
Standing Water       57
Sand/Mud/Dirt        47
Oil                  39
Name: ROADCOND, dtype: int64

In [21]:
final_df["LIGHTCOND"].value_counts()

Daylight                    71503
Dark - Street Lights On     29133
Unknown                      6062
Dusk                         3592
Dawn                         1535
Dark - No Street Lights       866
Dark - Street Lights Off      703
Other                         127
Dark - Unknown Lighting         7
Name: LIGHTCOND, dtype: int64

In [22]:
cleanup_nums = {"WEATHER": {"Clear": 1,"Raining": 2, "Overcast": 3, "Unknown": 4, "Snowing": 5, "Other": 6,"Fog/Smog/Smoke": 7, "Sleet/Hail/Freezing Rain": 8, "Blowing Sand/Dirt": 9, "Severe Crosswind": 10, "Partly Cloudy": 11},
                "ROADCOND": {"Dry": 1,"Wet": 2, "Unknown": 3, "Ice": 4, "Snow/Slush": 5, "Other": 6, "Standing Water": 7, "Sand/Mud/Dirt": 8, "Oil": 9},
                "LIGHTCOND": {"Daylight": 1, "Dark - Street Lights On": 2, "Unknown": 3, "Dusk": 4, "Dawn": 5, "Dark - No Street Lights": 6, "Dark - Street Lights Off": 7, "Other": 8, "Dark - Unknown Lighting": 9}}

In [34]:
import pandas as pd

In [23]:
final_df.replace(cleanup_nums, inplace=True)
final_df.head()

/opt/conda/envs/Python36/lib/python3.6/site-packages/pandas/core/generic.py:6517: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  regex=regex)


SEVERITYCODE  WEATHER  ROADCOND  LIGHTCOND
25055              1      2.0       2.0        2.0
65280              1      1.0       1.0        1.0
86292              1      4.0       3.0        3.0
155111             1      1.0       1.0        1.0
64598              1      1.0       1.0        1.0

In [24]:
final_df.head()

SEVERITYCODE  WEATHER  ROADCOND  LIGHTCOND
25055              1      2.0       2.0        2.0
65280              1      1.0       1.0        1.0
86292              1      4.0       3.0        3.0
155111             1      1.0       1.0        1.0
64598              1      1.0       1.0        1.0

In [25]:
final_df.dtypes

SEVERITYCODE      int64
WEATHER         float64
ROADCOND        float64
LIGHTCOND       float64
dtype: object

In [164]:
#Convert float64 to int64 format and continue with line 159

In [26]:
import pandas as pd
import numpy as np

In [27]:
final_df['WEATHER'] = pd.to_numeric(final_df['WEATHER'], errors='coerce').fillna(0)

/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [47]:
int_df = final_df["WEATHER"].astype(int)
int_df.dtypes


dtype('int64')

In [42]:
np.int64(final_df['ROADCOND'])

array([2, 1, 3, ..., 1, 1, 1])

In [44]:
np.int64(final_df['LIGHTCOND'])

array([2, 1, 3, ..., 1, 1, 4])

In [ ]:
numpy_data=np.int64(final_df['LIGHTCOND'])

In [45]:
final_df.dtypes

SEVERITYCODE      int64
WEATHER         float64
ROADCOND        float64
LIGHTCOND       float64
dtype: object

In [55]:
final_df = final_df.dropna()
print(final_df)

        SEVERITYCODE  WEATHER  ROADCOND  LIGHTCOND
25055              1      2.0       2.0        2.0
65280              1      1.0       1.0        1.0
86292              1      4.0       3.0        3.0
155111             1      1.0       1.0        1.0
64598              1      1.0       1.0        1.0
119954             1      1.0       1.0        1.0
64063              1      1.0       1.0        1.0
105379             1      1.0       1.0        1.0
187708             1      1.0       1.0        1.0
63021              1      4.0       3.0        1.0
156744             1      1.0       1.0        2.0
10240              1      1.0       1.0        4.0
37311              1      1.0       1.0        1.0
108465             1      1.0       1.0        1.0
97400              1      1.0       1.0        2.0
51928              1      2.0       2.0        2.0
7574               1      3.0       1.0        1.0
135430             1      6.0       3.0        3.0
64620              1      1.0  

In [56]:
print(final_df.round(0).astype(np.int64))

        SEVERITYCODE  WEATHER  ROADCOND  LIGHTCOND
25055              1        2         2          2
65280              1        1         1          1
86292              1        4         3          3
155111             1        1         1          1
64598              1        1         1          1
119954             1        1         1          1
64063              1        1         1          1
105379             1        1         1          1
187708             1        1         1          1
63021              1        4         3          1
156744             1        1         1          2
10240              1        1         1          4
37311              1        1         1          1
108465             1        1         1          1
97400              1        1         1          2
51928              1        2         2          2
7574               1        3         1          1
135430             1        6         3          3
64620              1        1  

In [58]:
final_df=final_df.round(0).astype(np.int64)

In [59]:
final_df.dtypes

SEVERITYCODE    int64
WEATHER         int64
ROADCOND        int64
LIGHTCOND       int64
dtype: object

In [ ]:
# Modeling and Predictions

In [60]:
x=np.asarray(final_df[['WEATHER', 'ROADCOND', 'LIGHTCOND']])
x[0:5]

array([[2, 2, 2],
       [1, 1, 1],
       [4, 3, 3],
       [1, 1, 1],
       [1, 1, 1]])

In [61]:
y=np.asarray(final_df['SEVERITYCODE'])
y[0:5]


array([1, 1, 1, 1, 1])

In [62]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.3, random_state=42)
print('Train set:', x_train.shape, y_train.shape)
print('Test set:', x_test.shape, y_test.shape)

Train set: (79447, 3) (79447,)
Test set: (34050, 3) (34050,)


In [68]:
# Building the KNN model
from sklearn.neighbors import KNeighborsClassifier
k=17

In [69]:
#Train Model & Predict
knn=KNeighborsClassifier(n_neighbors=k).fit(x_train, y_train)

knn_y_pred=knn.predict(x_test)
knn_y_pred[0:5]

array([2, 1, 1, 1, 1])

In [ ]:
# KNN Evaluation

In [72]:
from sklearn.metrics import jaccard_similarity_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss

In [74]:
jaccard_similarity_score(y_test, knn_y_pred)

0.5186490455212922

In [75]:
f1_score(y_test, knn_y_pred, average='macro')

0.5180780960740707

In [ ]:
# Decision Tree

In [79]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.externals.six import StringIO
import matplotlib.image as mpimg
from sklearn import tree

dt = DecisionTreeClassifier(criterion="entropy", max_depth = 7)
dt
dt.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=7,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [80]:
dt_y_pred = dt.predict(x_test)

In [ ]:
# Decision Tree Evaluation

In [81]:
jaccard_similarity_score(y_test, dt_y_pred)

0.5572393538913363

In [82]:
f1_score(y_test, dt_y_pred, average='macro')

0.48610939554341154

In [ ]:
# Linear Regression

In [84]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=6, solver='liblinear').fit(x_train, y_train)

In [85]:
LR_y_pred = LR.predict(x_test)

In [86]:
LR_y_prob = LR.predict_proba(x_test)

In [87]:
LR_y_prob = LR.predict_proba(x_test)
log_loss(y_test, LR_y_prob)

0.6818543944060274

In [ ]:
# Linear Regression Evaluation

In [88]:
jaccard_similarity_score(y_test, LR_y_pred)

0.5385315712187959

In [89]:
f1_score(y_test, LR_y_pred, average='macro')

0.5321816635757292

In [ ]:
# This concludes this Notebook! Thank you for reviewing.